first_task/apps/hotels/urls.py
from django.urls import path, include
from . import view

app_name = 'hotels'

urlpatterns = [
    path('', view.hotels, name='hotels'),
    path('<int:hotel_id>/', include([
        path('', view.hotel, name='hotel'),
        path('<int:id>/', view.room, name='room'),  # это id, не room_id
    ]))
]

first_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import view


urlpatterns = [
    path('hotels/', include('hotels.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', view.base_hotels, name='base_hotels')
]

first_task/apps/hotels/models.py
from django.db import models


class Hotel(models.Model):
    hotel_id = models.IntegerField('номер отеля')
    name = models.CharField('название отеля', max_length=150)
    city = models.CharField('название города', max_length=50)
    street = models.CharField('название улицы', max_length=50)
    house_number = models.CharField('номер дома', max_length=30)
    index = models.CharField('индекс почтового отделения', max_length=10)
    rooms_number = models.IntegerField('кол-во комнат')

    def __str__(self):
        return f"{self.name} (отель №{self.hotel_id})"


class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_id = models.IntegerField('номер комнаты')
    type = models.CharField('Тип комнаты(эконом, бизнес, люкс)', max_length=15)
    private_bath = models.BooleanField('Есть ли собственная ванна, True - есть, False - нет')
    private_toilet = models.BooleanField('Есть ли собственный туалет, True - есть, False - нет')
    sleeping_berth_number = models.DecimalField('Кол-во спальных мест, не больше 5', max_digits=5, decimal_places=0)
    double_bed = models.BooleanField('Есть ли двуспальная кровать, True - есть, False - нет')
    television_set = models.BooleanField('Есть ли телевизор, True - есть, False - нет')
    balcony = models.BooleanField('Есть ли балкон, True - есть, False - нет')

    def __str__(self):
        return f"{self.hotel.name}: {self.room_id}"

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

first_task/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sokolsky's hotels{% endblock %}</title>
</head>
<body>

    {% block content %}
        <p>
            <h1>Добро пожаловать на сайт Sokolsky's hotels</h1>
            <a href="hotels/">Здесь</a> выложена информация о наших отелях
        </p>
    {% endblock %}

</body>
</html>

first_task/templates/hotels/hotel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ h.name }}</title>
</head>
<body>
    {% block content %}
        <h1>
            Это страница отеля "{{ h.name }}"
        </h1>
        <p>
            Отель находится в городе {{ h.city }}, на улице {{ h.streer }} по номеру {{ h.house_number }}, а
            если вам необходим индекс ближайшего отделения почты - {{ h.index }}.
        </p>
        <p>
            Данный отель имеет {{ h.rooms_number }} комнат, 5 из которых типа "эконом", 3 "бизнес" и 2 "люкс".
        </p>
        <p>
            Вы можете посмотреть условия каждой комнаты кликнув по номеру комнаты снизу:
        </p>
        {% for n in r %}
            &nbsp;<a href="#">{{ n.room_id }}</a>&nbsp;
        {% endfor%}
    {% endblock %}
</body>
</html>

first_task/templates/hotels/hotels.html
{% extends 'base.html' %}

{% block title %}
    hotels
{% endblock %}

{% block content %}
    <p>
        Вот список существующих на данный момент отелей от Sokolsky's Hotels:
        {% if hotels_list %}
            {% for n in hotels_list %}
                <p>
                    <a href="{% url 'hotels:hotel' n.id %}">{{ n.name }}</a>
                </p>
            {% endfor %}
        {% else %}
            Отели не найдены
        {% endif %}
    </p>
{% endblock %}

first_task/templates/hotels/rooms/room.html
{% extends 'base.html' %}

{% block titile %} {{ h.name }}: room #{{ r.room_id }} {% endblock %}

{% block content %} hello there {% endblock %}